[package]
name = "nfsu2_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.2"
strum = "0.24.1"
strum_macros = "0.24"
device_query = "0.2.8"