use strum_macros::EnumIter;

#[derive(Debug, EnumIter)]
pub enum CircuitTracks {
    Freemont,
    Providencia,
    ResortLoop,
    LowerEastside,
    CityHall,
    Switchback,
    PalmHighway,
    Bellavista,
    BayviewSummit,
    Shoreside,
    AmbassadorRidge,
    FreewayWest,
    UniversityHill,
    Observatory,
    OuterRing,
    FreewayEast,
    MarineAnd25th,
    Dockside,
    Boxcar,
    Smokestack,
    BayviewConcrete,
    GrandviewStation,
    Jackpot,
    WoodbinePark,
    ParkDrive,
    _12thAndArtubus,
    BayviewInternational,
    GaribaldiRun,
    BroadStreet,
    ScenicRide,
    PhoenixSteel,
}
